apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/helm/release.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - image: gcr.io/jenkinsxio/jx-cli:3.0.773
          name: release-chart
          resources: {}
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            cd /workspace/source/charts/kubernetes-external-secrets
            make release
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}